init:
	uv run python -m app.utils.initial_data

run:
	uv run fastapi run app/main.py

migrate:
	uv run alembic upgrade head

createmigrations:
	uv run alembic revision --autogenerate -m "Autogenerated migration"

check:
	git add .
	uv run pre-commit run

test:
	uv run pytest tests/

pip:
	uv sync --all-extras --dev

update:
	uv run uv-bump
	uv sync --all-extras --dev
	uv run pre-commit autoupdate

ci: pip check test

docker-build:
	docker build -t david:latest .